# Generated by Django 4.2.3 on 2023-07-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article_image_alter_article_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='public',
            new_name='published',
        ),
    ]
